language: android

android:
  components:
    - android-22
    - build-tools-22.0.1 
    - extra-android-m2repository

jdk: 
  - oraclejdk7

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

script: ./gradlew build test --info